---
title: "Tutorial Stan usando a base imdb"
author: "Hanna Rodrigues Ferreira"
date: "`r format(Sys.time(), '%d %B,%Y')`"
output: 
    html_document:
        highlight: textmate 
        theme: flatly 
        toc: yes 
        number_sections: no
        toc_float:
            collapsed: yes
            smooth_scroll: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Baseada no tutorial: <https://mc-stan.org/users/documentation/case-studies/boarding_school_case_study.html>
 
 <https://betanalpha.github.io/assets/case_studies/identifying_mixture_models.html>
 
 <https://jeremy9959.net/Blog/StanMixture/>
 
 kaggle spotify

```{r, warning = FALSE, message = FALSE}

library(outbreaks)
library(tidyverse)
library(scales)

library(rstan)
library(gdata) # write
library(gridExtra)
rstan_options (auto_write = TRUE)
options (mc.cores = parallel::detectCores ())


library(tidybayes)
library(gridExtra)

library(rmarkdown)

```

```{r,echo=FALSE,warning=FALSE}

data <- read_csv("arquivos/data.csv")

data <- data %>% 
  filter(year>2000) %>%
  select(danceability,popularity,instrumentalness)

data <- data[1:1000,]

paged_table(data)

```



```{r}

data %>%
  ggplot() +
  geom_histogram(aes(x = instrumentalness),
                 fill = "steelblue",
                 color = "blue",
                 bins = 10)

```

```{r}

data %>%
  ggplot() +
  geom_histogram(aes(x = popularity),
                 fill = "steelblue",
                 color = "blue",
                 bins = 50)

ggsave("popularity.png")

```


```{r}

data <- data %>%
  select(popularity) %>%
  mutate(popularity = (popularity - mean(popularity))/sd(popularity))

y <- data$popularity

N <- length(data$popularity)

stan_data <- list(N = N, y = y)

```


```{r,warning=FALSE}

write("
data {
 int<lower = 0> N;
 vector[N] y;
}
parameters {
  vector[2] mu;
  real<lower=0> sigma[2];
  real<lower=0, upper=1> theta;
}
model { 
 sigma ~ normal(0,2);
 mu ~ normal(0,2);
 theta ~ normal(5,5);
 for (n in 1:N)
   target += log_mix(theta,
                     normal_lpdf(y[n] | mu[1], sigma[1]),
                     normal_lpdf(y[n] | mu[2], sigma[2]));
}
",
"mixture_gaussian.stan")

```



```{r}

fit <- stan(file="mixture_gaussian.stan",data=stan_data)

```


```{r}

print(fit,separate_chains = TRUE)

```

```{r}

stan_dens(fit,separate_chains = TRUE)

ggsave("dens_chains.png")

traceplot(fit)

ggsave("traceplot.png")

```



```{r}

params1 <- as.data.frame(extract(fit, permuted=FALSE)[,1,])

p <- c(mean(params1$`mu[1]`),
       mean(params1$`mu[2]`),
       mean(params1$`sigma[1]`),
       mean(params1$`sigma[2]`),
       mean(params1$theta) )


y_pred <- (1 - p[5]) * dnorm(x = seq(1,N,1),c(p[1],p[3])) + p[5] * dnorm(x = seq(1,N,1),c(p[2],p[4]))


data %>%
  ggplot(aes(x = popularity)) +
  geom_histogram(fill = "steelblue",
                 color = "blue",
                 bins = 50) 

```
